name: CI

on:
  push:
  pull_request:

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pb1-broken-api .

      - name: Run tests inside Docker container
        run: docker run --rm pb1-broken-api python -m pytest